import { createClient } from '@supabase/supabase-js'
const URL=import.meta.env.VITE_SUPABASE_URL, KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const configured=URL&&KEY&&!URL.includes('YOUR_PROJECT');
const supabase=configured?createClient(URL,KEY):null;
const app=document.querySelector('#app'); let state={user:null,profile:null,athletes:[],sessions:[],bookings:[],view:'home'};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
const fmt=d=>new Date(d).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function shell(body){return `<div class="shell"><header class="top"><div class="brand"><img src="/assets/logo.png"><span>iTrainSpeed</span></div><div class="row"><span>${state.profile?.full_name||state.user?.email||'Guest'}</span>${state.user?'<button class="pill" data-act="logout">Sign out</button>':''}</div></header><main class="wrap">${state.user?nav():''}${body}</main>${state.user?bottom():''}</div>`}
function nav(){let items=['home','book','sessions','performance']; if(['coach','admin'].includes(state.profile?.role))items.push('coach');return `<div class="nav desktopnav">${items.map(x=>`<button class="${state.view===x?'active':''}" data-view="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div>`}
function bottom(){return `<div class="bottom">${['home','book','sessions','performance'].map(x=>`<button data-view="${x}">${x==='home'?'⌂':x==='book'?'＋':x==='sessions'?'▣':'↗'}<br>${x}</button>`).join('')}</div>`}
function render(){if(!configured)return setup(); if(!state.user)return auth(); const views={home,book,sessions,performance,coach}; app.innerHTML=shell((views[state.view]||home)()); bind()}
function setup(){app.innerHTML=shell(`<div class="auth"><img src="/assets/logo.png"><h2>Connect iTrainSpeed</h2><p>This production build is ready for Supabase. Add your project URL and anon key to <b>.env</b>, then run the app.</p><div class="notice">Copy <b>.env.example</b> to <b>.env</b> and add your Supabase values. Never place the Stripe secret key in this file.</div></div>`)}
function auth(){app.innerHTML=shell(`<div class="auth"><img src="/assets/logo.png"><h2>Welcome to iTrainSpeed</h2><p class="muted">Sign in to book training and track athlete performance.</p><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Password</label><input id="password" type="password"></div><div class="row"><button class="btn" data-act="signin">Sign in</button><button class="btn secondary" data-act="signup">Create account</button></div><div id="msg"></div></div>`);bind()}
function home(){const next=state.bookings.filter(b=>b.status==='booked').sort((a,b)=>new Date(a.sessions.start_at)-new Date(b.sessions.start_at))[0];return `<section class="hero"><h1>Train with purpose.</h1><p>Book training, track progress, and keep your athlete moving forward.</p></section><div class="grid"><section class="card"><span class="muted">NEXT SESSION</span>${next?`<h2>${next.sessions.programs.name}</h2><p>${fmt(next.sessions.start_at)}</p><button class="btn" data-view="sessions">View booking</button>`:'<div class="empty">No upcoming bookings.<br><button class="btn" data-view="book">Book training</button></div>'}</section><section class="card"><span class="muted">ATHLETES</span><div class="metric">${state.athletes.length}</div><p class="muted">Profiles connected to your account</p><button class="btn secondary" data-act="add-athlete">Add athlete</button></section><section class="card wide"><div class="row space"><div><span class="muted">TRAINING CREDITS</span><div class="metric">${state.profile?.credits??0}</div></div><button class="btn" data-act="buy">Buy package</button></div></section></div>`}
function book(){const aid=state.athletes[0]?.id;return `<section class="hero"><h1>Book Training</h1><p>Live iTrainSpeed sessions and availability.</p></section><div class="card wide">${!aid?'<div class="empty">Add an athlete before booking.<br><button class="btn" data-act="add-athlete">Add athlete</button></div>':state.sessions.length?state.sessions.map(s=>`<div class="session"><div><b>${s.programs.name}</b><div>${fmt(s.start_at)}</div><small class="muted">${s.location||'iTrainSpeed'} • Ages ${s.min_age}-${s.max_age} • ${s.booked_count||0}/${s.capacity} booked</small></div><div><span class="tag">${s.credit_cost||1} credit</span> <button class="btn" data-act="book" data-id="${s.id}">Book</button></div></div>`).join(''):'<div class="empty">No published sessions available.</div>'}</div>`}
function sessions(){return `<section class="hero"><h1>My Sessions</h1></section><div class="card wide">${state.bookings.length?state.bookings.map(b=>`<div class="session"><div><b>${b.sessions.programs.name}</b><div>${fmt(b.sessions.start_at)}</div><small class="muted">${b.athletes.first_name} • ${b.status}</small></div>${b.status==='booked'?`<button class="btn secondary" data-act="cancel" data-id="${b.id}">Cancel</button>`:''}</div>`).join(''):'<div class="empty">No bookings yet.</div>'}</div>`}
function performance(){return `<section class="hero"><h1>Performance</h1><p>PRs and athlete development.</p></section><div class="grid">${state.athletes.map(a=>`<section class="card"><span class="muted">ATHLETE</span><h2>${a.first_name} ${a.last_name||''}</h2><p>${a.sport||'Athlete'} • Age ${a.age||'—'}</p><button class="btn secondary">View results</button></section>`).join('')||'<section class="card wide empty">Add an athlete to begin tracking performance.</section>'}</div>`}
function coach(){if(!['coach','admin'].includes(state.profile?.role))return '<div class="notice">Coach access required.</div>';return `<section class="hero"><h1>Booking Control Center</h1><p>Create sessions, manage capacity and run the daily roster.</p></section><div class="grid"><section class="card"><h3>Create Session</h3><div class="field"><label>Program</label><select id="program">${[...new Map(state.sessions.map(s=>[s.programs.id,s.programs])).values()].map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div class="field"><label>Date & time</label><input id="start" type="datetime-local"></div><div class="field"><label>Capacity</label><input id="capacity" type="number" value="10"></div><button class="btn" data-act="create-session">Publish session</button></section><section class="card"><span class="muted">UPCOMING SESSIONS</span><div class="metric">${state.sessions.length}</div><p>Published sessions currently available for booking.</p></section><section class="card wide"><h3>Live Schedule</h3>${state.sessions.map(s=>`<div class="session"><div><b>${s.programs.name}</b><div>${fmt(s.start_at)}</div></div><b>${s.booked_count||0}/${s.capacity}</b></div>`).join('')}</section></div>`}
async function load(){const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(!state.user)return render();let {data:p}=await supabase.from('profiles').select('*').eq('id',state.user.id).single();state.profile=p;let {data:a}=await supabase.from('athletes').select('*').eq('guardian_id',state.user.id).order('created_at');state.athletes=a||[];let {data:s}=await supabase.from('session_availability').select('*').gte('start_at',new Date().toISOString()).eq('status','published').order('start_at').limit(50);state.sessions=s||[];let {data:b}=await supabase.from('bookings').select('*, athletes(*), sessions(*, programs(*))').eq('guardian_id',state.user.id).order('created_at',{ascending:false});state.bookings=b||[];render()}
function bind(){document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;render()});document.querySelectorAll('[data-act]').forEach(el=>el.onclick=()=>act(el.dataset.act,el.dataset.id))}
async function act(a,id){try{if(a==='signin'||a==='signup'){let email=document.querySelector('#email').value,password=document.querySelector('#password').value;let r=a==='signin'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)throw r.error;return load()}if(a==='logout'){await supabase.auth.signOut();state={...state,user:null,profile:null};return render()}if(a==='add-athlete'){let first=prompt('Athlete first name');if(!first)return;let age=Number(prompt('Age'));let sport=prompt('Primary sport')||'';let {error}=await supabase.from('athletes').insert({guardian_id:state.user.id,first_name:first,age,sport});if(error)throw error;return load()}if(a==='book'){let athlete=state.athletes[0];if(!athlete)return;let {error}=await supabase.rpc('book_session',{p_session_id:id,p_athlete_id:athlete.id});if(error)throw error;alert('Booked!');return load()}if(a==='cancel'){let {error}=await supabase.rpc('cancel_booking',{p_booking_id:id});if(error)throw error;return load()}if(a==='buy'){let {data,error}=await supabase.functions.invoke('create-checkout-session',{body:{package_key:'group_10'}});if(error)throw error;if(data?.url)location.href=data.url;else alert('Stripe checkout is ready after you add your Stripe secrets and Price IDs in Supabase.')}if(a==='create-session'){let program_id=document.querySelector('#program').value,start_at=document.querySelector('#start').value,capacity=+document.querySelector('#capacity').value;let {error}=await supabase.from('sessions').insert({program_id,start_at:new Date(start_at).toISOString(),duration_minutes:60,capacity,status:'published',location:'iTrainSpeed',created_by:state.user.id});if(error)throw error;return load()}}catch(e){alert(e.message||String(e))}}
if(supabase)supabase.auth.onAuthStateChange(()=>setTimeout(load,0));load();
